language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

before_install:
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls
  - go get -u -v golang.org/x/tools/cmd/cover

script:
  - $GOPATH/bin/goveralls -service=travis-ci
